admin_products:
  - Discount
  - Manual
  - AMAZON FEE
  - Amamzon
  - DOTCOM POSTAGE
  - POSTAGE
  - Bank Charges
  - CRUK Commission
  - Adjust bad debt
  - SAMPLES
  - check
  - ebay
  - Found
  - "?"
  - missing
  - "?missing"
  - adjustment
  - sold as 1
  - mailout
